### ISSUE TITLE
Question: Can I use similar method to just get directory sizes rather than file sizes?

### ISSUE THREAD

**Issue by PCAssistSoftware** [bsonnino/NtfsFileEnum#2]
Firstly fantastic project, very interesting.

Question: 

Can I use similar method to just get directory sizes rather than file sizes?  so I can quickly see what directories are using a lot of space on a system?

If so any clues as to what I would need to modify please?

**Comment by bsonnino** [comment]
Yes, you can do it, I will make a change to the project to make it in the next days

**Comment by PCAssistSoftware** [comment]
Thank you that would be much appreciated

**Comment by bsonnino** [comment]
I've checked the code and it's already sorting by directory size when you select "Folder" in the sort combobox. It does that using WPF grouping features. If you want to get only the directories size (and not the files sizes), you can change the code to:

```
List<(string, Int64)> newNodes = null;
await Task.Factory.StartNew(() =>
{
    var ntfsReader =
        new NtfsReader(driveToAnalyze, RetrieveMode.All);
    
    newNodes = ntfsReader.GetNodes(driveToAnalyze.Name)
            .Where(n => (n.Attributes &
                         (Attributes.Hidden | Attributes.System |
                          Attributes.Temporary | Attributes.Device |
                          Attributes.Directory | Attributes.Offline |
                          Attributes.ReparsePoint | Attributes.SparseFile)) == 0)
            .GroupBy(n => Path.GetDirectoryName(n.FullName))
            .Select(g => (g.Key, g.Sum(n => (Int64)n.Size)))
            .OrderByDescending(n => n.Item2).ToList();
});
```
newNodes will be a tuple with the name of the directory and the total size, sorted by the size of the directory in descending order

**Comment by PCAssistSoftware** [comment]
Hi, thanks for response

I assume this code replaces in

 private async void DrvCombo_SelectionChanged(object sender, 
            System.Windows.Controls.SelectionChangedEventArgs e)

If so then code is not quite right as getting various errors - see below

I suspect I can just rename nodes to newNodes or vice versa to fix 3 of them but not sure how to sort the Int64 error

37 The type or namespace name 'Int64' could not be found (are you missing a using directive or an assembly reference?)	NtfsFileEnum	C:\Users\darre\Downloads\NtfsFileEnum-master\NtfsFileEnum-master\NtfsFileEnum\MainWindow.xaml.cs

50 The type or namespace name 'Int64' could not be found (are you missing a using directive or an assembly reference?)	NtfsFileEnum	C:\Users\darre\Downloads\NtfsFileEnum-master\NtfsFileEnum-master\NtfsFileEnum\MainWindow.xaml.cs

54 The name 'nodes' does not exist in the current context	NtfsFileEnum	C:\Users\darre\Downloads\NtfsFileEnum-master\NtfsFileEnum-master\NtfsFileEnum\MainWindow.xaml.cs		

58 The name 'nodes' does not exist in the current context	NtfsFileEnum	C:\Users\darre\Downloads\NtfsFileEnum-master\NtfsFileEnum-master\NtfsFileEnum\MainWindow.xaml.cs		

59 The name 'nodes' does not exist in the current context	NtfsFileEnum	C:\Users\darre\Downloads\NtfsFileEnum-master\NtfsFileEnum-master\NtfsFileEnum\MainWindow.xaml.cs

![image](https://user-images.githubusercontent.com/10872799/93865034-a413c900-fcbd-11ea-944c-b2ba3e2933f5.png)


Would appreciate some input

**Comment by PCAssistSoftware** [comment]
And when it sorts by folder, can I choose depth as need to sort by size of folder but be able to drill down each level e.g. sub folders of Program Files (x86) etc?

Thanks again

**Comment by bsonnino** [comment]
There are many changes to be done in the code, I just pointed the direction. The code I've shown doesn't allow to select the depth, it will go to the last level of the folder. Here's what I'll do - In the next days I'll write another article and will create another project that will allow to do what you are expecting. I'll put here the links for both.

**Comment by PCAssistSoftware** [comment]
Thank you, that is very kind of you, I really appreciate it as using this method is so much quicker than scanning through all files using System.IO.Directory / DirectoryInfo with GetFiles/GetDirectories or EnumerateFiles/EnumerateDirectories.  I just want to be able to run it quickly so I can see size of folders to work out which folders contain the most data etc 👍

**Comment by PCAssistSoftware** [comment]
"The code I've shown doesn't allow to select the depth, it will go to the last level of the folder. "

For me quite happy for it to full depth e.g. last level of folder, but could be useful I suspect to be able to choose for others

**Comment by bsonnino** [comment]
I've written an article [here ](https://blogs.msmvps.com/bsonnino/2020/09/26/discover-what-is-consuming-your-disk-with-ntfs-structures/) about transforming the code to get the directories that are consuming your disk. The accompanying project is [here](https://github.com/bsonnino/NtfsDirectories)

**Comment by PCAssistSoftware** [comment]
Thank you so much, have just downloaded it - have a couple of suggestions which I will open on the new project 👍
